<?xml version="1.0" encoding="utf-8"?><Database Name="mylibrary" Class="MyLibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0I1PU5A;Initial Catalog=mylibrary;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="mylibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.books" Member="books">
    <Type Name="book">
      <Column Name="book_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="last_edited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>